### ISSUE TITLE
Support for ON/OFF Temperature of Comet

### ISSUE THREAD

**Issue by DerOetzi** [foxthefox/ioBroker.fritzdect#14]
Hi,

I'm really new to iobroker, so I don't know a solution for this yet. I noticed that there is a problem with the targettemp Object if I change the value of the Comet to either ON or OFF which is above 28°C or below 8°C or in holiday mode,

It would be nice if you can implement support for setting the comet to off state, for example for automation scripts for example for summer mode or window sensors

Thanks in advance

Johannes

**Comment by foxthefox** [comment]
Please check the version from github and provide feedback. I do not own the thermostats.

Best regards
Klaus

**Comment by DerOetzi** [comment]
Thanks for the quick reply.

I think a boolean state is not enough, because there a three states at least:

0. Off = Permanent closed
1. "Auto" = Thermostats holds the adjusted targettemp between 8 and 28 degrees
2. On = Permanent opened

Maybe an enum or integer value would be more suitable for this.

Best regards

Johannes

I will try to do a matching widget for this. Can I make a branch on your repository and send you a pull request when I'm finished with it.

**Comment by foxthefox** [comment]
Did it at least work with the boolean states?
That was my understanding what is required. I mean in the senso of automatic control is in operation or manual.
Because there is no specific command for OFF/ON the bool state is transferred to a value of 253=OFF and 254=ON on the command for setpoint.
When "Auto" is needed only a valid temperature must be given and it is in AUTO.
I could split the state into two single datapoints off/on and then a 3 option radio button could be used, but what binary value should be on the "AUTO" button??

You can make a branch an commit pull requests, no problem.

Bets regards
Klaus

**Comment by DerOetzi** [comment]
Hi,

unfortunately the state value is not filled. I will check some more things and will make a suggestion for review on a seperate branch then. 

As I explained the thermostat knows three different states Closed (Off), Regulation to targettemp (Auto), Open (On) so I thing this cannot be represented by an boolean state. 

I will do some research and come back to you.

Best regards

Johannes

**Comment by foxthefox** [comment]
done with merge
